<?php

namespace Database\Seeders;

use App\Models\WcagSuccessCriterion;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class WcagSuccessCriteriaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $criteria = [
            ['number' => '1.1.1', 'level' => 'A', 'name_en' => 'Non-text Content', 'name_sv' => 'Icke-textinnehål', 'description_en' => 'All non-text content that is presented to the user has a text alternative that serves the equivalent purpose.', 'description_sv' => 'Allt icke-textinnehål som presenteras för användaren har en textalternativ som uppfyller motsvarande syfte.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/1.1.1.html'],
            ['number' => '1.2.1', 'level' => 'A', 'name_en' => 'Audio-only and Video-only (Prerecorded)', 'name_sv' => 'Endast ljud och endast video (inspelad)', 'description_en' => 'For prerecorded audio-only and prerecorded video-only media, an alternative or an audio track is provided.', 'description_sv' => 'För inspelad endast-ljud och inspelad endast-video-media tillhandahålls ett alternativ eller ett ljudspår.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/1.2.1.html'],
            ['number' => '1.2.2', 'level' => 'A', 'name_en' => 'Captions (Prerecorded)', 'name_sv' => 'Textning (inspelad)', 'description_en' => 'Captions are provided for all prerecorded audio content in synchronized media.', 'description_sv' => 'Textning tillhandahålls för allt inspelat audioinnehål i synkroniserad media.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/1.2.2.html'],
            ['number' => '1.2.3', 'level' => 'A', 'name_en' => 'Audio Description or Media Alternative (Prerecorded)', 'name_sv' => 'Audiobeskrivning eller mediealternativ (inspelad)', 'description_en' => 'An alternative or audio description is provided for all prerecorded video content in synchronized media.', 'description_sv' => 'Ett alternativ eller audiobeskrivning tillhandahålls för allt inspelat videoinnehål i synkroniserad media.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/1.2.3.html'],
            ['number' => '1.2.4', 'level' => 'AA', 'name_en' => 'Captions (Live)', 'name_sv' => 'Textning (direkt)', 'description_en' => 'Captions are provided for all live audio content in synchronized media.', 'description_sv' => 'Textning tillhandahålls för allt direktljudinnehål i synkroniserad media.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/1.2.4.html'],
            ['number' => '1.2.5', 'level' => 'AA', 'name_en' => 'Audio Description (Prerecorded)', 'name_sv' => 'Audiobeskrivning (inspelad)', 'description_en' => 'Audio description is provided for all prerecorded video content in synchronized media.', 'description_sv' => 'Audiobeskrivning tillhandahålls för allt inspelat videoinnehål i synkroniserad media.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/1.2.5.html'],
            ['number' => '1.3.1', 'level' => 'A', 'name_en' => 'Info and Relationships', 'name_sv' => 'Information och relationer', 'description_en' => 'Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text.', 'description_sv' => 'Information, struktur och relationer som förmedlas genom presentationen kan programmässigt bestämmas eller finns tillgänglig i text.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/1.3.1.html'],
            ['number' => '1.3.2', 'level' => 'A', 'name_en' => 'Meaningful Sequence', 'name_sv' => 'Meningsfull ordning', 'description_en' => 'When the sequence in which content is presented affects its meaning, a correct reading sequence can be programmatically determined.', 'description_sv' => 'När ordningen i vilken innehåll presenteras påverkar dess betydelse kan en korrekt läsordning programmässigt bestämmas.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/1.3.2.html'],
            ['number' => '1.3.3', 'level' => 'A', 'name_en' => 'Sensory Characteristics', 'name_sv' => 'Sensoriska egenskaper', 'description_en' => 'Instructions provided for understanding and operating content do not rely solely on the shape, size, or visual location of components.', 'description_sv' => 'Instruktioner för förståelse och användning av innehåll förlitar sig inte enbart på form, storlek eller visuell plats för komponenter.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/1.3.3.html'],
            ['number' => '1.4.1', 'level' => 'A', 'name_en' => 'Use of Color', 'name_sv' => 'Färganvändning', 'description_en' => 'Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element.', 'description_sv' => 'Färg används inte som det enda visuella sättet att förmedla information, indikera en åtgärd, fråga efter ett svar eller skilja ett visuellt element.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/1.4.1.html'],
            ['number' => '1.4.2', 'level' => 'A', 'name_en' => 'Audio Control', 'name_sv' => 'Audiokontroll', 'description_en' => 'If any audio on a Web page plays automatically for more than 3 seconds, either a mechanism is available to pause or stop the audio, or a mechanism is available to control audio volume.', 'description_sv' => 'Om något ljud på en webbsida spelas automatiskt i mer än 3 sekunder finns det antingen en mekanism för att pausa eller stoppa ljudet, eller en mekanism för att kontrollera ljudvolymen.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/1.4.2.html'],
            ['number' => '1.4.3', 'level' => 'AA', 'name_en' => 'Contrast (Minimum)', 'name_sv' => 'Kontrast (minimum)', 'description_en' => 'The visual presentation of text and images of text has a contrast ratio of at least 4.5:1.', 'description_sv' => 'Den visuella presentationen av text och textbilder har ett kontrastförhållande på minst 4,5:1.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/1.4.3.html'],
            ['number' => '1.4.4', 'level' => 'AA', 'name_en' => 'Resize text', 'name_sv' => 'Ändra storlek på text', 'description_en' => 'Except for captions and images of text, text can be resized without loss of content or functionality up to 200 percent.', 'description_sv' => 'Förutom bildtexter och textbilder kan text ändras upp till 200 procent utan förlust av innehål eller funktionalitet.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/1.4.4.html'],
            ['number' => '2.1.1', 'level' => 'A', 'name_en' => 'Keyboard', 'name_sv' => 'Tangentbord', 'description_en' => 'All functionality of the content is operable via a keyboard interface without requiring specific timings for individual keystrokes.', 'description_sv' => 'All funktionalitet för innehållet kan användas via ett tangentbordsgränssnitt utan att kräva specifik timing för individuella tangenttryckningar.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/2.1.1.html'],
            ['number' => '2.1.2', 'level' => 'A', 'name_en' => 'No Keyboard Trap', 'name_sv' => 'Ingen tangentbordsfälla', 'description_en' => 'If keyboard focus can be moved to a component of the page using a keyboard interface, then focus can be moved away from that component using only a keyboard interface.', 'description_sv' => 'Om tangentbordsfokus kan flyttas till en del av sidan med ett tangentbordsgränssnitt kan fokus flyttas bort från den komponenten med endast ett tangentbordsgränssnitt.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/2.1.2.html'],
            ['number' => '2.4.1', 'level' => 'A', 'name_en' => 'Bypass Blocks', 'name_sv' => 'Kringgå block', 'description_en' => 'A mechanism is available to bypass blocks of content that are repeated on multiple Web pages.', 'description_sv' => 'En mekanism finns tillgänglig för att kringgå block av innehål som upprepas på flera webbsidor.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/2.4.1.html'],
            ['number' => '2.4.2', 'level' => 'A', 'name_en' => 'Page Titled', 'name_sv' => 'Sidan är rubricerad', 'description_en' => 'Web pages have titles that describe topic or purpose.', 'description_sv' => 'Webbsidor har titlar som beskriver ämne eller syfte.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/2.4.2.html'],
            ['number' => '2.4.3', 'level' => 'A', 'name_en' => 'Focus Order', 'name_sv' => 'Fokusordning', 'description_en' => 'If a Web page can be navigated sequentially and the navigation sequences affect meaning or operation, focusable components receive focus in an order that preserves meaning and operability.', 'description_sv' => 'Om en webbsida kan navigeras sekventiellt och navigationsekvenserna påverkar betydelse eller användning får fokuserbara komponenter fokus i en ordning som bevarar betydelse och användbarhet.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/2.4.3.html'],
            ['number' => '2.4.4', 'level' => 'A', 'name_en' => 'Link Purpose (In Context)', 'name_sv' => 'Länkens syfte (i sammanhang)', 'description_en' => 'The purpose of each link can be determined from the link text alone or from the link text together with its programmatically determined link context.', 'description_sv' => 'Syftet med varje länk kan bestämmas från länktexten ensam eller från länktexten tillsammans med sitt programmässigt bestämda länksammanhang.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/2.4.4.html'],
            ['number' => '2.4.7', 'level' => 'AA', 'name_en' => 'Focus Visible', 'name_sv' => 'Fokus synligt', 'description_en' => 'Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible.', 'description_sv' => 'Alla användarinterfaces som kan användas med tangentbord har ett driftläge där tangentbordsfokusindikatorn är synlig.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/2.4.7.html'],
            ['number' => '3.1.1', 'level' => 'A', 'name_en' => 'Language of Page', 'name_sv' => 'Språk för sida', 'description_en' => 'The default human language of each Web page can be programmatically determined.', 'description_sv' => 'Det förvalda människokspråket för varje webbsida kan programmässigt bestämmas.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/3.1.1.html'],
            ['number' => '3.2.1', 'level' => 'A', 'name_en' => 'On Focus', 'name_sv' => 'Vid fokus', 'description_en' => 'When any component receives focus, it does not initiate a change of context.', 'description_sv' => 'När någon komponent får fokus initierar den inte en kontextförändring.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/3.2.1.html'],
            ['number' => '3.2.2', 'level' => 'A', 'name_en' => 'On Input', 'name_sv' => 'Vid inmatning', 'description_en' => 'Changing the setting of any user interface component does not automatically cause a change of context unless the user has been advised of the behavior.', 'description_sv' => 'Ändring av inställningen för någon användarinterfacekomponent orsakar inte automatiskt en kontextförändring om inte användaren har underrättats om beteendet.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/3.2.2.html'],
            ['number' => '3.3.1', 'level' => 'A', 'name_en' => 'Error Identification', 'name_sv' => 'Felidentifiering', 'description_en' => 'If an input error is automatically detected, the item that is in error is identified and the error is described to the user in text.', 'description_sv' => 'Om ett inmatningsfel automatiskt upptäcks identifieras objektet som är felaktigt och felet beskrivs för användaren i text.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/3.3.1.html'],
            ['number' => '3.3.2', 'level' => 'A', 'name_en' => 'Labels or Instructions', 'name_sv' => 'Etiketter eller instruktioner', 'description_en' => 'Labels or instructions are provided when content requires user input.', 'description_sv' => 'Etiketter eller instruktioner tillhandahålls när innehål kräver användarinmatning.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/3.3.2.html'],
            ['number' => '4.1.2', 'level' => 'A', 'name_en' => 'Name, Role, Value', 'name_sv' => 'Namn, roll, värde', 'description_en' => 'For all user interface components, the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.', 'description_sv' => 'För alla användarinterfacekomponenter kan namn och roll programmässigt bestämmas; tillstånd, egenskaper och värden som kan ställas av användaren kan programmässigt ställas in; och meddelande om ändringar av dessa objekt är tillgängligt för användaragenter, inklusive hjälpmedelsteknologi.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/4.1.2.html'],
            ['number' => '4.1.3', 'level' => 'AA', 'name_en' => 'Status Messages', 'name_sv' => 'Statusmeddelanden', 'description_en' => 'In content implemented using markup languages, status messages can be programmatically determined through role or properties such that they can be presented to the user by assistive technologies without receiving focus.', 'description_sv' => 'I innehål implementerat med markeringsspråk kan statusmeddelanden programmässigt bestämmas genom roll eller egenskaper så att de kan presenteras för användaren av hjälpmedelsteknologi utan att få fokus.', 'url' => 'https://www.w3.org/WAI/WCAG21/Understanding/4.1.3.html'],
        ];

        foreach ($criteria as $criterion) {
            $criterion['id'] = \Illuminate\Support\Str::ulid();
            WcagSuccessCriterion::firstOrCreate(['number' => $criterion['number']], $criterion);
        }
    }
}
