@php use App\Models\AccessibilityProject; @endphp

<flux:header>
    <flux:heading>{{ __('Reports for :name', ['name' => $project->name]) }}</flux:heading>
    <flux:spacer/>
    <flux:button href="{{ route('accessibility-projects.show', $project) }}" variant="ghost" icon="arrow-left">{{ __('Back') }}</flux:button>
</flux:header>

<flux:main class="space-y-6">
    <div class="flex justify-end">
        <flux:button href="{{ route('accessibility-reports.create', $project) }}" variant="primary" icon="plus">
            {{ __('Generate Report') }}
        </flux:button>
    </div>

    @if ($reports->isEmpty())
        <flux:card class="text-center py-12">
            <flux:icon name="document-text" class="w-12 h-12 mx-auto mb-4 text-zinc-400"/>
    <p class="text-zinc-600 dark:text-zinc-400">{{ __('No reports generated yet.') }}</p>
            <flux:button href="{{ route('accessibility-reports.create', $project) }}" variant="primary" class="mt-4">
        {{ __('Generate First Report') }}
            </flux:button>
        </flux:card>
    @else
        <flux:table>
            <flux:table.columns>
                <flux:table.cell>{{ __('Title') }}</flux:table.cell>
                <flux:table.cell>{{ __('Issues') }}</flux:table.cell>
                <flux:table.cell>{{ __('Generated By') }}</flux:table.cell>
                <flux:table.cell>{{ __('Date') }}</flux:table.cell>
                <flux:table.cell>{{ __('Actions') }}</flux:table.cell>
            </flux:table.columns>

            @foreach ($reports as $report)
                <flux:table.row>
                    <flux:table.cell>{{ $report->title }}</flux:table.cell>
                    <flux:table.cell>
                        <flux:badge>{{ $report->total_issues }} {{ __('Issues') }}</flux:badge>
                    </flux:table.cell>
                    <flux:table.cell>{{ $report->creator->name }}</flux:table.cell>
                    <flux:table.cell>{{ $report->created_at->format('M d, Y') }}</flux:table.cell>
                    <flux:table.cell class="flex gap-2">
                        <flux:button href="{{ route('accessibility-reports.show', ['project' => $project, 'report' => $report]) }}" variant="ghost" icon="eye" size="sm">
                        {{ __('Preview') }}
                        </flux:button>
                        <flux:button href="{{ route('accessibility-reports.download', ['project' => $project, 'report' => $report]) }}" variant="ghost" icon="arrow-down-tray" size="sm">
                        {{ __('Download') }}
                        </flux:button>
                        <form action="{{ route('accessibility-reports.destroy', ['project' => $project, 'report' => $report]) }}" method="POST" style="display: inline;" onsubmit="return confirm('{{ __('Are you sure?') }}');">
                            @csrf
                            @method('DELETE')
                            <flux:button type="submit" variant="ghost" icon="trash" size="sm" class="text-red-600">
                            {{ __('Delete') }}
                            </flux:button>
                        </form>
                    </flux:table.cell>
                </flux:table.row>
            @endforeach
        </flux:table>
    @endif
</flux:main>
