@php use App\Models\AccessibilityProject; @endphp

<flux:header>
    <flux:heading>{{ __('Reports for :name', ['name' => $project-> {{ __('') }} <flux:button href="{{ route('accessibility-projects.show', $project) }}" variant="ghost" icon="arrow-left">{{ __('Back') }}</flux:button> {{ __('') }} <div class="flex justify-end">
        <flux:button href="{{ route('accessibility-reports.create', $project) }}" variant="primary" icon="plus">
            {{ __('Generate Report') }}
        </flux:button>
    </div>

    @if ($reports-> {{ __('') }} <p class="text-zinc-600 dark:text-zinc-400">{{ __('No reports generated yet.') }}</p>
            <flux:button href="{{ route('accessibility-reports.create', $project) }}" variant="primary" class="mt-4">
        {{ __('Generate First Report') }}
            </flux:button>
        </flux:card> {{ __('') }} <flux:table.cell>{{ __('Title') }}</flux:table.cell>
                <flux:table.cell>{{ __('Issues') }}</flux:table.cell>
                <flux:table.cell>{{ __('Generated By') }}</flux:table.cell>
                <flux:table.cell>{{ __('Date') }}</flux:table.cell>
                <flux:table.cell>{{ __('Actions') }}</flux:table.cell>
            </flux:table.columns> {{ __('') }} </flux:table.cell> {{ __('') }} </flux:badge> {{ __('') }} </flux:table.cell>
                    <flux:table.cell>{{ $report->created_at-> {{ __('') }} <flux:button href="{{ route('accessibility-reports.show', ['project' => $project, 'report' => $report]) }}" variant="ghost" icon="eye" size="sm">
                        {{ __('Preview') }}
                        </flux:button>
                        <flux:button href="{{ route('accessibility-reports.download', ['project' => $project, 'report' => $report]) }}" variant="ghost" icon="arrow-down-tray" size="sm">
                        {{ __('Download') }}
                        </flux:button>
                        <form action="{{ route('accessibility-reports.destroy', ['project' => $project, 'report' => $report]) }}" method="POST" style="display: inline;" onsubmit="return confirm('{{ __('Are you sure?') }}');">
                            @csrf
                            @method('DELETE')
                            <flux:button type="submit" variant="ghost" icon="trash" size="sm" class="text-red-600">
                            {{ __('Delete') }}
                            </flux:button> {{ __('') }} </flux:table.row>
            @endforeach
        </flux:table>
    @endif
</flux:main>
